FROM archlinux:latest

ENV QT_QPA_PLATFORM=offscreen

RUN sed -i 's/^#ParallelDownloads = 5/ParallelDownloads = 5/' /etc/pacman.conf && \
    echo 'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist && \
    pacman -Syu --noconfirm && pacman -S --noconfirm --needed \
    base-devel \
    gcc \
    cmake \
    ninja \
    qt6-base \
    qt6-declarative \
    qt6-svg \
    layer-shell-qt \
    xorg-server-xvfb \
    dbus \
    bc \
    hicolor-icon-theme \
    && rm -rf /var/cache/pacman/pkg/*

WORKDIR /src
COPY . /src

RUN mkdir -p /src/build && \
    cmake -B /src/build -S /src -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr && \
    cmake --build /src/build && \
    ctest --test-dir /src/build --output-on-failure && \
    cmake --install /src/build

RUN chmod +x /src/tests/containers/entrypoint_test.sh

ENTRYPOINT ["/src/tests/containers/entrypoint_test.sh"]
